<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Lab_1</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Font\bigdonstarve.ttf" />
    <None Remove="Images\back1.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Icons\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Font\bigdonstarve.ttf" />
    <Resource Include="Images\back1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
